USE cliffHangerClimbingGyms;
GO
ALTER TABLE Customers WITH CHECK
ADD CONSTRAINT FK_Zipcode FOREIGN KEY(Zipcode) REFERENCES Zipcode(Zipcode)
ON UPDATE CASCADE
GO
ALTER TABLE Gyms WITH CHECK
ADD CONSTRAINT FK_Gym_Zipcode FOREIGN KEY(Zipcode) REFERENCES Zipcode(Zipcode)
ON UPDATE NO ACTION
GO
ALTER TABLE Sales 
ADD CONSTRAINT FK_GymID FOREIGN KEY(GymID) REFERENCES Gyms(GymID)
ON UPDATE CASCADE
GO
ALTER TABLE Sales 
ADD CONSTRAINT FK_CustomerID FOREIGN KEY(CustomerID) REFERENCES Customers(CustomerID)
ON UPDATE CASCADE
GO
ALTER TABLE Employees WITH CHECK
ADD CONSTRAINT FK_HomeGymID FOREIGN KEY(HomeGymID) REFERENCES Gyms(GymID)
ON UPDATE CASCADE
GO
ALTER TABLE GymRoutes 
ADD CONSTRAINT FK_RouteGymID FOREIGN KEY(RouteGymID) REFERENCES Gyms(GymID)
ON UPDATE NO ACTION
--GO
ALTER TABLE GymRoutes 
ADD CONSTRAINT FK_EmployeeID FOREIGN KEY(EmployeeID) REFERENCES Employees(EmployeeID)
ON UPDATE CASCADE
ON DELETE CASCADE
--GO
ALTER TABLE SalesDetails 
ADD CONSTRAINT FK_SaleID FOREIGN KEY(SalesID) REFERENCES Sales(SaleID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE SalesDetails 
ADD CONSTRAINT FK_ProductID FOREIGN KEY(ProductID) REFERENCES Inventory(ProductID)
ON UPDATE CASCADE
